### ISSUE TITLE
Multiple binaries share the same codesign path when trying to Export archive for distribution

### ISSUE THREAD

**Issue by sparta-developers** [sparta-science/connect#48] opened 2020-08-07 17:36 UTC
```
2020-08-07 17:29:24 +0000  Failed to generate distribution items with error: Error Domain=IDEFoundationErrorDomain Code=1 "/Users/Sparta/Library/Developer/Xcode/Archives/2020-08-07/archive.xcarchive/Products contains invalid products." UserInfo={NSLocalizedDescription=/Users/Sparta/Library/Developer/Xcode/Archives/2020-08-07/archive.xcarchive/Products contains invalid products., NSLocalizedRecoverySuggestion=Multiple binaries share the same codesign path:
/Applications/SpartaConnect.app/Contents/Frameworks/Testable.framework/Versions/Current

Binaries:
/Applications/SpartaConnect.app/Contents/Frameworks/Testable.framework/Versions/Current/Testable
/Applications/SpartaConnect.app/Contents/Frameworks/Testable.framework/Testable

This can happen if your build process copies frameworks by following symlinks. }

```

When using artifact from this build: https://github.com/sparta-science/connect/actions/runs/198848063

**Comment by paulz** [comment] 2020-08-11 00:36
This issue was caused by incorrectly archiving folders with symbolic links, which became files instead of links.
Fixed by using `ditto` to archive as it preserves symbolic links: https://github.com/sparta-science/connect/commit/f329749d5beb27f64f15a27ecbdf59b3a615317c#diff-c355746c943879db0e8a9d8c8c4bae3aR8

**Closed by paulz** 2020-08-11 00:36 UTC
